version: '3.3'
services:
  es01:
    image: elasticsearch:7.14.1
    container_name: es01_con
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: kibana:7.14.1
    container_name: kibana_con
    ports:
      - 5601:5601
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS="http://es01:9200"
    depends_on:
      - es01

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge